apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-connection
  name: api-connection
spec:
  ports:
  - name: api-connection
    nodePort: 30009
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api-connection
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-connection
  name: api-connection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-connection
  strategy: {}
  template:
    metadata:
      labels:
        app: api-connection
    spec:
      containers:
      - image: newthingade/api_connections:v1
        name: api-connection
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
