apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-people
  name: api-people
spec:
  ports:
  - name: api-people
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30002
  selector:
    app: api-people
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-people
  name: api-people
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-people
  template:
    metadata:
      labels:
        app: api-people
    spec:
      containers:
      - image: newthingade/api_people:v1
        name: api-people
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
